<?php

use App\Http\Controllers\Api\AboutContentController;
use App\Http\Controllers\Api\AboutDashController;
use App\Http\Controllers\Api\AboutSubjectController;
use App\Http\Controllers\Api\AboutTitleController;
use App\Http\Controllers\Api\BankCardController;
use App\Http\Controllers\Api\BlockedUserController;
use App\Http\Controllers\Api\CartController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\CommentController;
use App\Http\Controllers\Api\CustomerOrderController;
use App\Http\Controllers\Api\FileController;
use App\Http\Controllers\Api\GroupController;
use App\Http\Controllers\Api\HashtagController;
use App\Http\Controllers\Api\HistoryController;
use App\Http\Controllers\Api\MediaController;
use App\Http\Controllers\Api\MessageController;
use App\Http\Controllers\Api\MoneyTransferController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\PasswordResetController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\PricingController;
use App\Http\Controllers\Api\PricingDescriptionController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\PromoCodeController;
use App\Http\Controllers\Api\ReactionController;
use App\Http\Controllers\Api\ReasonController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\SubscriptionController;
use App\Http\Controllers\Api\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::post('users/login', [UserController::class, 'login']);
    Route::get('users/username/{username}', [UserController::class, 'findByUsername']);
    Route::get('users/search/by-word', [UserController::class, 'search']);
    Route::patch('users/{user}/status', [UserController::class, 'updateStatus']);
    Route::patch('users/{user}/password', [UserController::class, 'updatePassword']);
    Route::patch('users/{user}/type', [UserController::class, 'updateType']);
    Route::patch('users/{user}/avatar', [UserController::class, 'updateAvatar']);
    Route::post('password-resets/find-user', [PasswordResetController::class, 'findUser']);
    Route::post('password-resets/check-token', [PasswordResetController::class, 'checkToken']);
    Route::get('medias/popular/list', [MediaController::class, 'popularMedias']);
    Route::patch('medias/{media}/publish', [MediaController::class, 'publishMedia']);
    Route::get('medias/{media}/views', [MediaController::class, 'mediaViews']);
    Route::get('medias/{media}/likes', [MediaController::class, 'mediaLikes']);
    Route::get('medias/{media}/gifts', [MediaController::class, 'mediaGifts']);
    Route::post('medias/{media}/like', [MediaController::class, 'like']);
    Route::post('medias/{media}/gift', [MediaController::class, 'gift']);
    Route::post('medias/{media}/report', [MediaController::class, 'report']);
    Route::apiResource('users', UserController::class);
    Route::apiResource('roles', RoleController::class);
    Route::apiResource('categories', CategoryController::class);
    Route::apiResource('reasons', ReasonController::class);
    Route::apiResource('pricings', PricingController::class);
    Route::apiResource('pricing-descriptions', PricingDescriptionController::class);
    Route::apiResource('medias', MediaController::class);
    Route::apiResource('products', ProductController::class);
    Route::apiResource('groups', GroupController::class);
    Route::apiResource('messages', MessageController::class);
    Route::apiResource('files', FileController::class);
    Route::apiResource('notifications', NotificationController::class);
    Route::apiResource('promo-codes', PromoCodeController::class);
    Route::apiResource('about-subjects', AboutSubjectController::class);
    Route::apiResource('about-titles', AboutTitleController::class);
    Route::apiResource('about-contents', AboutContentController::class);
    Route::apiResource('about-dashes', AboutDashController::class);
    Route::apiResource('blocked-users', BlockedUserController::class);
    Route::apiResource('money-transfers', MoneyTransferController::class);
    Route::apiResource('histories', HistoryController::class);
    Route::apiResource('subscriptions', SubscriptionController::class);
    Route::apiResource('reports', ReportController::class);
    Route::apiResource('hashtags', HashtagController::class);
    Route::apiResource('reactions', ReactionController::class);
    Route::apiResource('bank-cards', BankCardController::class);
    Route::apiResource('carts', CartController::class);
    Route::apiResource('customer-orders', CustomerOrderController::class);
    Route::apiResource('comments', CommentController::class);
    Route::apiResource('payments', PaymentController::class);
});
